services:
  minecraft:
    image: "minecraft-papermc-server:latest"
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "1G"
      TZ: "Europe/Moscow"
      PAPERMC_FLAGS: ""
      LOGGING_HOST: "172.17.0.1"
      LOGGING_PORT: "514"
      LOGGING_PROTOCOL: "UDP"
    volumes:
      - "/home/evseyantonovich/mcserver:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
